`ifndef PO_PORTS_SV
`define PO_PORTS_SV

`timescale 1ns / 1ns
interface HCBCtrl_ports 
import definitions_pkg::*;
(
input logic clock, 
output logic resetN,
output logic enable,
output logic stop,
output logic waiting_out,
output k_t k,
output pad_t stride,
output logic doBM,
output logic doRelu,
output logic doLRelu, 
output logic doRes,
output logic isOnOutput,
output logic reset_isOnOutput, // finished one output
output logic BM_enough_data,
output logic w_enough_data,
output res_size_t receivedRes,
output res_size_t totalRes,
output logic input_fifo_empty,
output layer_addr_t readCLast,
output logic new_conv_inst,
output layer_addr_t Ks,
output layer_addr_t kt,
output cg_addr_t new_wtotal,
output cg_addr_t numGroups,
output logic reset_state,
output logic resetLoadingNextFeatures,
output logic resetReadingFeatures,
output logic new_params_prefetch,
output logic setLoadingFroze,
output logic resetLoadingFroze,
output width_t writeWidth,
output logic resetAssemble,
output width_t new_readWidth,
output width_t new_outputBufH1,
output s_row_addr_t new_rowNum,
output loc_frame_t prefetchFrameSize,
output layer_addr_t new_kCur,
output cg_addr_t new_usedGroups,
output k_t inst_k,
output layer_addr_t kOut,
output layer_addr_t kCurLast,
output cg_addr_t usedGroupsLast,
output cg_addr_t wtotal_n,
output weight_bus_size_t wlenk_nLast,
output cg_addr_t wtotalLast,
output weight_bus_size_t wlenk_nLast2,
output weight_bus_size_t wlenk_regular,
output weight_bus_size_t wlen_regular,
output weight_bus_size_t new_wlenk,
output weight_bus_size_t new_wlenk_last,
output layer_addr_t kCurLast_1,
output width1_t new_maxRowCount,
output width_t new_lastLen,

input logic startPrefetching,
input logic startConvOut, 
input weight_bus_size_t BMlen, 
input weight_bus_size_t wlenk,
input logic enSendBMWeights,
input logic enSendWeights,
input logic isBMWeightValid,
input logic isWeightValid,
input cg_addr_t weightId,
input logic sendBackUpInput_valid,
input k_t backupId,
input logic isOutputReady,
input logic nextWeight,
input width_t readWidth,
input s_row_addr_t rowNum,
input logic reset_iLayers,
input logic loadNextInst,
input logic isPrefetchNextVolume_next,
input logic isPrefetchNextVolume,
input layer_addr_t workingProgress_o,
input logic doAssemble_o,
input input_addr_t usedWords_o,
input logic isInitLayer_o,
input logic isReadingFeatures_o,
input logic isLoadingFroze_o,
input logic hasNextFeatureParams_o,
input logic isLoadingNextFeatures_o,
input logic isLReluWeight_o,
input k_t iterCountDown_o,
input width_t outputReadPos_o,
input width_t outputWritePos_o,
input HCB_STATE state_o,
input HCB_STATE state_next_o,
input width_t outputBufH1_o,
input logic isNextVolumeReady_o,
input logic bmPhase_o,
input logic isRunning_o,
input logic is_cycle_froze,
input width1_t maxRowCount,
input width_t lastLen,
input INPUT_SOURCE input_src
);
endinterface



`endif
