vlog -reportprogress 300 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/pkg.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/ram_fifo.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/dmem_32_16/dmem_32_16_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/inputs_mem/inputs_mem_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_assemble_buffer/fifo_assemble_buffer_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_bmweights/fifo_bmweights_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_weights/fifo_weights_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_resdata/fifo_resdata_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionHCB/fifo_InstructionHCB_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionHCBWt/fifo_InstructionHCBWt_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/interface/fifo_out_addrs_sizes.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionEnd/fifo_InstructionEnd_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlread_data/fifo_ctrlread_data_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlread_info/fifo_ctrlread_info_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlread_req/fifo_ctrlread_req_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlread_ret/fifo_ctrlread_ret_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionRead/fifo_InstructionRead_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlweight_data/fifo_ctrlweight_data_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionWeight/fifo_InstructionWeight_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/ctrlweight_mem/ctrlweight_mem_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlwrite_addr/fifo_ctrlwrite_addr_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_DDRReadInfo/fifo_DDRReadInfo_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_DDRWriteInfo/fifo_DDRWriteInfo_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_ctrlwrite_data/fifo_ctrlwrite_data_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/ip/fifo_InstructionWrite/fifo_InstructionWrite_sim_netlist.v
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/cloud/fifo_addressBuffer.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/cloud/fifo_DDR_Load_Info.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/readExtra.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/readFeatures.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/resFifo.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/ddrwriteassist.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/ddrreadassist.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/SCG.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/sendBackUpInput.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/setupShiftInputs.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/startConvOut.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/UCL.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/UCU.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/weightFifo.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/assembleInput.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/assembleInputBuffer.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/BMWeightFifo.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/buildInputFifo.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/HCBCtrl.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/processConvOut.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/processInstruction.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/processNextFeatureLoading.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/processNextWeightLoading.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/pushHCBInst.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/HCB.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/Token.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/GIB.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/ctrlread.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/ctrlwrite.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/new/ctrlweight.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/interface/DDR.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/interface/if_test.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/cloud/cloud.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/xilinx2/cloud_driver.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/xilinx2/cloud_top.sv
vlog -reportprogress 30 -work work C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/xilinx2/cloud_tb.sv
vsim -L unisims_ver -gui -novopt cloud_tb  work.glbl
#vsim -debugDB -L D:/modeltech64_10.2c/XilinxLib/Xilinx_Corelib -gui -novopt -sv_lib C:/AI/AIFPGA/sv/sv.srcs/sources_1/sim/cloud/svdpi cloud_tb 
